local L = LibStub ("AceLocale-3.0"):NewLocale ("RaidAssistAddon", "ruRU", true) 
if not L then return end

L["S_PLUGIN_COOLDOWNS_RAID_CDS"] = "Рейдовые кулдауны:"
L["S_PLUGIN_COOLDOWNS_EXTERNAL_CDS"] = "Внешние кулдауны:"
L["S_PLUGIN_COOLDOWNS_SPELLNAME"] = "Отслеживание времени восстановления для %s"

L["S_PLUGIN_ATTENDANCE_NAME"] = "Посещаемость"
L["S_PLUGIN_ATTENDANCE_NO_DATA"] = "Там нет данных для отображения, нажмите, чтобы настроить этот плагин."

L["S_PLUGIN_BRES_NAME"] = "Отслеживания Воскрешения в Бою"
L["S_PLUGIN_BRES_POPUP_DESC"] = "Нажмите, чтобы открыть панель параметров."
L["S_PLUGIN_BRES_SHOW_HISTORY"] = "Показать историю воскрешений"
L["S_PLUGIN_BRES_SHOW_HISTORY_DESC"] = "Показывает, кто получил боевое воскрешение во время текущей битвы с боссом."

L["S_PLUGIN_BOARDS_NAME"] = "Доска"

L["S_ENABLED"] = "Включено"
L["S_PLUGIN_ENABLED"] = "Плагин включен"
L["S_PLUGIN_ENABLED_DESC"] = "Включен ли этот плагин или нет."

L["S_COLOR"] = "Цвет"
L["S_HEIGHT"] = "Увеличивать"
L["S_GROW_INVERSE"] = "Уменьшать"

L["S_PLUGIN_TEXT_SHADOW"] = "Тень текста"
L["S_PLUGIN_TEXT_FONT"] = "Шрифт текста"
L["S_PLUGIN_TEXT_SIZE"] = "Размер текста"
L["S_PLUGIN_TEXT_COLOR"] = "Цвет текста"
L["S_PLUGIN_TEXT_ANCHOR"] = "Закрепить текст"
L["S_PLUGIN_FRAME_LOCKED"] = "Рамка заблокирована"
L["S_PLUGIN_FRAME_BACKDROP_COLOR"] = "Цвет рамки"
L["S_PLUGIN_FRAME_BORDER_COLOR"] = "Цвет границы"
L["S_PLUGIN_COLOR_CLASS"] = "Цвет по классу"
L["S_PLUGIN_FRAME_LOCKED_DESC"] = "Если включено, рамка не может быть перемещена."

L["S_ANCHOR_ONLY_IN_ENCOUNTER"] = "В бою с боссом"
L["S_ANCHOR_ONLY_IN_COMBAT"] = "В бою"
L["S_ANCHOR_ONLY_IN_INSTANCES"] = "Внутри подземелья"
L["S_ANCHOR_ONLY_IN_RAID"] = "В Рейде"
L["S_ANCHOR_ONLY_IN_GROUP"] = "В Группе"
L["S_ANCHOR_ONLY_IN_RAID_DESC"] = "Когда эта опция включена, панель закрепления отображается только тогда, когда вы находитесь в рейд-группе."
L["S_ANCHOR_SIDE"] = "Размер закрепления"
L["S_ANCHOR_SIDE_DESC"] = "На какой стороне экрана будет закрепление."
L["S_ANCHOR_SIZE"] = "Размер закрепления"
L["S_ANCHOR_SIZE_DESC"] = "Расширение в пикселях закрепления."
L["S_ANCHOR_COLOR"] = "Цвет закрепления"
L["S_ANCHOR_COLOR_DESC"] = "Цвет закрепления."
L["S_ANCHOR_Y"] = "Позиция (лево-право)"
L["S_ANCHOR_Y_DESC"] = "Установите положение, когда закрепление произведено с левой или правой стороны."
L["S_ANCHOR_X"] = "Позиция (верх-низ)"
L["S_ANCHOR_X_DESC"] = "Установите положение, когда закрепление произведено сверху или снизу."
L["S_ANCHOR_LEFT"] = "лево"
L["S_ANCHOR_RIGHT"] = "право"
L["S_ANCHOR_TOP"] = "верх"
L["S_ANCHOR_BOTTOM"] = "низ"
L["S_ANCHOR_CENTER"] = "центр"

L["S_EQUIPSLOT_1"] = "Голова"
L["S_EQUIPSLOT_2"] = "Шея"
L["S_EQUIPSLOT_3"] = "Плечо"
L["S_EQUIPSLOT_5"] = "Грудь"
L["S_EQUIPSLOT_6"] = "Пояс"
L["S_EQUIPSLOT_7"] = "Ноги"
L["S_EQUIPSLOT_8"] = "Ступни"
L["S_EQUIPSLOT_9"] = "Запястья"
L["S_EQUIPSLOT_10"] = "Кисти рук"
L["S_EQUIPSLOT_11"] = "Кольцо"
L["S_EQUIPSLOT_13"] = "Аксессуар"
L["S_EQUIPSLOT_15"] = "Спина"
L["S_EQUIPSLOT_16"] = "Оружие"
