L["S_PLUGIN_COOLDOWNS_RAID_CDS"] = "Рейдовое восстановление:"
L["S_PLUGIN_COOLDOWNS_EXTERNAL_CDS"] = "Внешнее восстановление:"
L["S_PLUGIN_COOLDOWNS_SPELLNAME"] = "Отслеживайте время восстановления %s"

L["S_PLUGIN_ATTENDANCE_NAME"] = "Посещаемость"
L["S_PLUGIN_ATTENDANCE_NO_DATA"] = "Нет данных для отображения, нажмите, чтобы настроить этот плагин."

L["S_PLUGIN_BRES_NAME"] = "Отображение воскрешений"
L["S_PLUGIN_BRES_POPUP_DESC"] = "Щелкните, чтобы открыть панель параметров."
L["S_PLUGIN_BRES_SHOW_HISTORY"] = "Показать историю воскрешений"
L["S_PLUGIN_BRES_SHOW_HISTORY_DESC"] = "Показывает, кто получил воскрешение во время текущего боя с боссом."

L["S_PLUGIN_BOARDS_NAME"] = "Советы"

L["S_ENABLED"] = "Включено"
L["S_PLUGIN_ENABLED"] = "Плагин включен"
L["S_PLUGIN_ENABLED_DESC"] = "Включен этот плагин или нет."

L["S_COLOR"] = "Цвет"
L["S_HEIGHT"] = "Высота"
L["S_GROW_INVERSE"] = "Уменьшение"

L["S_PLUGIN_TEXT_SHADOW"] = "Тень текста"
L["S_PLUGIN_TEXT_FONT"] = "Шрифт текста"
L["S_PLUGIN_TEXT_SIZE"] = "Размер текста"
L["S_PLUGIN_TEXT_COLOR"] = "Цвет текста"
L["S_PLUGIN_TEXT_ANCHOR"] = "Якорь текста"
L["S_PLUGIN_FRAME_LOCKED"] = "Рамка заблокировано"
L["S_PLUGIN_FRAME_BACKDROP_COLOR"] = "Цвет рамки"
L["S_PLUGIN_FRAME_BORDER_COLOR"] = "Цвет границы"
L["S_PLUGIN_COLOR_CLASS"] = "Цвет по классу"
L["S_PLUGIN_FRAME_LOCKED_DESC"] = "Если включено, рамка не может быть перемещена."

L["S_ANCHOR_ONLY_IN_ENCOUNTER"] = "В столкновении с боссом"
L["S_ANCHOR_ONLY_IN_COMBAT"] = "В бою"
L["S_ANCHOR_ONLY_IN_INSTANCES"] = "Внутри подземелья"
L["S_ANCHOR_ONLY_IN_RAID"] = "В рейде"
L["S_ANCHOR_ONLY_IN_GROUP"] = "В группе"
L["S_ANCHOR_ONLY_IN_RAID_DESC"] = "Если этот параметр включен, панель закрепления отображается только тогда, когда вы находитесь в рейдовой группе."
L["S_ANCHOR_SIDE"] = "Сторона закрепления"
L["S_ANCHOR_SIDE_DESC"] = "С какой стороны экрана будет осуществлено закрепление."
L["S_ANCHOR_SIZE"] = "Размер закрепления"
L["S_ANCHOR_SIZE_DESC"] = "Размер закрепления в пикселях."
L["S_ANCHOR_COLOR"] = "Цвет закрепления"
L["S_ANCHOR_COLOR_DESC"] = "Цвет закрепления."
L["S_ANCHOR_Y"] = "Положение (слева-справа)"
L["S_ANCHOR_Y_DESC"] = "Установите положение, когда закрепление прикреплено с левой или правой стороны."
L["S_ANCHOR_X"] = "Положение (верх-низ)"
L["S_ANCHOR_X_DESC"] = "Установите положение, когда закрепление прикреплено сверху или снизу."
L["S_ANCHOR_LEFT"] = "лево"
L["S_ANCHOR_RIGHT"] = "право"
L["S_ANCHOR_TOP"] = "вверх"
L["S_ANCHOR_BOTTOM"] = "низ"
L["S_ANCHOR_CENTER"] = "центр"

L["S_EQUIPSLOT_1"] = "Голова"
L["S_EQUIPSLOT_2"] = "Шея"
L["S_EQUIPSLOT_3"] = "Плечо"
L["S_EQUIPSLOT_5"] = "Грудь"
L["S_EQUIPSLOT_6"] = "Пояс"
L["S_EQUIPSLOT_7"] = "Ноги"
L["S_EQUIPSLOT_8"] = "Ступни"
L["S_EQUIPSLOT_9"] = "Запястья"
L["S_EQUIPSLOT_10"] = "Кисти рук"
L["S_EQUIPSLOT_11"] = "Палец"
L["S_EQUIPSLOT_13"] = "Аксессуар"
L["S_EQUIPSLOT_15"] = "Плащ"
L["S_EQUIPSLOT_16"] = "Оружие"